services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    ports: 
      - '5432:5432'
    volumes:
      - myapp-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'


  app:
    build:
      context: myapp
    # For development, volume mount code
    volumes:
      - ./myapp:/rails
    links:
      - postgres
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env

  sidekiq:
    build:
      context: myapp
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:1.25
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/conf.d/reverse-proxy.conf:ro
    links:
      - app
    ports:
      - '8080:8080'

volumes:
  myapp-postgres:
  myapp-redis:
